# Generated by Django 5.2.15 on 2026-06-08 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inbox", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="meta", max_length=64)),
                ("app_id", models.CharField(blank=True, default="", max_length=128)),
                (
                    "page_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                (
                    "business_account_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "phone_number_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("access_token_encrypted", models.TextField(blank=True, default="")),
                (
                    "verify_token",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("app_secret_encrypted", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel_account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credential",
                        to="inbox.channelaccount",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_credentials",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["channel_account__channel_type"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_type", models.CharField(max_length=32)),
                (
                    "external_event_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "external_message_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "event_type",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("normalized_json", models.JSONField(blank=True, default=dict)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("ignored", "Ignored"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("duplicate", "Duplicate"),
                        ],
                        default="received",
                        max_length=32,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_events",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
    ]
