# Generated by Django 5.2.15 on 2026-06-08 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0002_phase11_channel_mock_and_webhook_conversation"),
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookevent",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="webhook_events",
                to="inbox.conversation",
            ),
        ),
    ]
