# Generated by Django 5.2.15 on 2026-06-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelaccount",
            name="mock_mode",
            field=models.BooleanField(
                default=True,
                help_text="When enabled, channel uses local mock mode without real Meta API calls.",
            ),
        ),
    ]
