# Generated by Django 5.2.15 on 2026-06-08 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=128)),
                (
                    "priority_label",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("market_need_score", models.PositiveSmallIntegerField(default=0)),
                ("tags_json", models.JSONField(blank=True, default=list)),
                ("default_workflow_json", models.JSONField(blank=True, default=dict)),
                ("default_prompt", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("is_implemented", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-market_need_score", "name"],
            },
        ),
        migrations.CreateModel(
            name="AgentInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("language", models.CharField(default="en", max_length=16)),
                ("tone", models.CharField(default="professional", max_length=64)),
                ("ai_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_instances",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="agents.agenttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("tenant", "template", "name")},
            },
        ),
        migrations.CreateModel(
            name="AgentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("business_description", models.TextField(blank=True, default="")),
                ("services_json", models.JSONField(blank=True, default=list)),
                ("pricing_json", models.JSONField(blank=True, default=dict)),
                (
                    "qualification_questions_json",
                    models.JSONField(blank=True, default=list),
                ),
                ("objection_handling_json", models.JSONField(blank=True, default=dict)),
                ("handoff_rules_json", models.JSONField(blank=True, default=dict)),
                ("working_hours_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="agents.agentinstance",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Agent settings",
            },
        ),
    ]
